set(BUILD_DEMOS OFF CACHE BOOL)
set(INSTALL_DEMOS OFF CACHE BOOL)
set(BUILD_SHARED OFF CACHE BOOL)
set(BUILD_STATIC ON CACHE BOOL)
set(INSTALL_STATIC OFF CACHE BOOL)

add_subdirectory(thirdparty/Chipmunk2D)
