# build options
set(BUILD_SHARED_LIBS OFF)
set(CUSTOMIZE_BUILD ON)

# core
set(SUPPORT_CAMERA_SYSTEM ON)
set(SUPPORT_GESTURES_SYSTEM OFF)
set(SUPPORT_MOUSE_GESTURES OFF)
set(SUPPORT_SSH_KEYBOARD_RPI OFF)
set(SUPPORT_DEFAULT_FONT ON)
set(SUPPORT_SCREEN_CAPTURE ON)
set(SUPPORT_GIF_RECORDING ON)
set(SUPPORT_BUSY_WAIT_LOOP OFF)
set(SUPPORT_EVENTS_WAITING OFF)
set(SUPPORT_WINMM_HIGHRES_TIMER OFF)
set(SUPPORT_DATA_STORAGE ON)
set(SUPPORT_COMPRESSION_API OFF)

# shapes
set(SUPPORT_QUADS_DRAW_MODE ON)

# textures
set(SUPPORT_IMAGE_EXPORT OFF)
set(SUPPORT_IMAGE_GENERATION OFF)
set(SUPPORT_IMAGE_MANIPULATION ON)
set(SUPPORT_FILEFORMAT_PNG ON)
set(SUPPORT_FILEFORMAT_DDS OFF)
set(SUPPORT_FILEFORMAT_HDR OFF)
set(SUPPORT_FILEFORMAT_KTX OFF)
set(SUPPORT_FILEFORMAT_ASTC OFF)
set(SUPPORT_FILEFORMAT_BMP OFF)
set(SUPPORT_FILEFORMAT_TGA OFF)
set(SUPPORT_FILEFORMAT_JPG OFF)
set(SUPPORT_FILEFORMAT_GIF OFF)
set(SUPPORT_FILEFORMAT_PSD OFF)
set(SUPPORT_FILEFORMAT_PKM OFF)
set(SUPPORT_FILEFORMAT_PVR OFF)

# text
set(SUPPORT_FILEFORMAT_FNT OFF)
set(SUPPORT_FILEFORMAT_TTF ON)
set(SUPPORT_TEXT_MANIPULATION ON)

# models
set(SUPPORT_MESH_GENERATION OFF)
set(SUPPORT_FILEFORMAT_OBJ OFF)
set(SUPPORT_FILEFORMAT_MTL OFF)
set(SUPPORT_FILEFORMAT_IQM OFF)
set(SUPPORT_FILEFORMAT_GLTF OFF)

# raudio
set(SUPPORT_FILEFORMAT_WAV ON)
set(SUPPORT_FILEFORMAT_OGG OFF)
set(SUPPORT_FILEFORMAT_XM ON)
set(SUPPORT_FILEFORMAT_MOD OFF)
set(SUPPORT_FILEFORMAT_MP3 OFF)
set(SUPPORT_FILEFORMAT_FLAC OFF)

# utils
set(SUPPORT_STANDARD_FILEIO OFF)
set(SUPPORT_TRACELOG ON)

add_subdirectory(raylib)