name: Ubuntu

on: [push]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install Dependencies
      # https://github.com/raysan5/raylib/wiki/Working-on-GNU-Linux
      run: sudo apt update && sudo apt install build-essential upx-ucl libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev -y

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Optimize Binary
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        strip --strip-all ${{runner.workspace}}/build/4mb_platformer
        upx --best ${{runner.workspace}}/build/4mb_platformer

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 4mb_platformer
        path: ${{runner.workspace}}/build/4mb_platformer
