name: macOS

on: [push]

env:
  BUILD_TYPE: MinSizeRel
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install Dependencies
      # https://github.com/raysan5/raylib/wiki/Working-on-macOS
      run: brew install upx

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Optimize Binary
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        strip --strip-all ${{runner.workspace}}/build/4mb_platformer
        upx --best ${{runner.workspace}}/build/4mb_platformer

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 4mb_platformer
        path: ${{runner.workspace}}/build/4mb_platformer